# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 581)
        MainWindow.setStyleSheet("background-color: rgb(36, 42, 56);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QToolTip { \n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(36, 42, 56); \n"
"  border: black solid 1px\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signalsBtn = QtWidgets.QCheckBox(self.layoutWidget)
        self.signalsBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.signalsBtn.setFont(font)
        self.signalsBtn.setStyleSheet("QCheckBox\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"  background-color: rgb(255, 255, 255);\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  border-radius: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    border-image: url(:/Icons/GUI_Resources/check.svg);\n"
"}\n"
"\n"
"QCheckBox::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}")
        self.signalsBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signalsBtn.setIcon(icon)
        self.signalsBtn.setIconSize(QtCore.QSize(25, 25))
        self.signalsBtn.setObjectName("signalsBtn")
        self.horizontalLayout.addWidget(self.signalsBtn)
        self.vpwvBtn = QtWidgets.QCheckBox(self.layoutWidget)
        self.vpwvBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.vpwvBtn.setFont(font)
        self.vpwvBtn.setStyleSheet("QCheckBox\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"  background-color: rgb(255, 255, 255);\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  border-radius: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    border-image: url(:/Icons/GUI_Resources/check.svg);\n"
"}\n"
"\n"
"QCheckBox::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"")
        self.vpwvBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/activity.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vpwvBtn.setIcon(icon1)
        self.vpwvBtn.setIconSize(QtCore.QSize(25, 25))
        self.vpwvBtn.setObjectName("vpwvBtn")
        self.horizontalLayout.addWidget(self.vpwvBtn)
        self.triggerBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.triggerBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.triggerBtn.setFont(font)
        self.triggerBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"")
        self.triggerBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/zap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.triggerBtn.setIcon(icon2)
        self.triggerBtn.setIconSize(QtCore.QSize(25, 25))
        self.triggerBtn.setObjectName("triggerBtn")
        self.horizontalLayout.addWidget(self.triggerBtn)
        self.dopplerBtn = QtWidgets.QCheckBox(self.layoutWidget)
        self.dopplerBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.dopplerBtn.setFont(font)
        self.dopplerBtn.setStyleSheet("QCheckBox\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"  background-color: rgb(255, 255, 255);\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  border-radius: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    border-image: url(:/Icons/GUI_Resources/check.svg);\n"
"}\n"
"\n"
"QCheckBox::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}")
        self.dopplerBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/tv.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dopplerBtn.setIcon(icon3)
        self.dopplerBtn.setIconSize(QtCore.QSize(25, 25))
        self.dopplerBtn.setObjectName("dopplerBtn")
        self.horizontalLayout.addWidget(self.dopplerBtn)
        self.userMarkersBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.userMarkersBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.userMarkersBtn.setFont(font)
        self.userMarkersBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"")
        self.userMarkersBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/flag.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userMarkersBtn.setIcon(icon4)
        self.userMarkersBtn.setIconSize(QtCore.QSize(25, 25))
        self.userMarkersBtn.setObjectName("userMarkersBtn")
        self.horizontalLayout.addWidget(self.userMarkersBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TitleLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("color: rgb(131, 152, 203);")
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveBtn = QtWidgets.QCheckBox(self.layoutWidget)
        self.saveBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("QCheckBox\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"  background-color: rgb(255, 255, 255);\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  border-radius: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked\n"
"{\n"
"    border-image: url(:/Icons/GUI_Resources/check.svg);\n"
"}\n"
"\n"
"QCheckBox::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 10px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}")
        self.saveBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon5)
        self.saveBtn.setIconSize(QtCore.QSize(25, 25))
        self.saveBtn.setChecked(True)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.settingsBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(10)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}")
        self.settingsBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsBtn.setIcon(icon6)
        self.settingsBtn.setIconSize(QtCore.QSize(25, 25))
        self.settingsBtn.setObjectName("settingsBtn")
        self.horizontalLayout.addWidget(self.settingsBtn)
        self.fullscreenBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.fullscreenBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"")
        self.fullscreenBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.fullscreenBtn.setIcon(icon7)
        self.fullscreenBtn.setIconSize(QtCore.QSize(25, 25))
        self.fullscreenBtn.setCheckable(True)
        self.fullscreenBtn.setObjectName("fullscreenBtn")
        self.horizontalLayout.addWidget(self.fullscreenBtn)
        self.exitBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.exitBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 0px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"")
        self.exitBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon8)
        self.exitBtn.setIconSize(QtCore.QSize(25, 25))
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plot1 = SignalsPlotter(self.layoutWidget)
        self.plot1.setObjectName("plot1")
        self.verticalLayout.addWidget(self.plot1)
        self.plot2 = SignalsPlotter(self.layoutWidget)
        self.plot2.setObjectName("plot2")
        self.verticalLayout.addWidget(self.plot2)
        self.plot3 = vpwvPlotter(self.layoutWidget)
        self.plot3.setObjectName("plot3")
        self.verticalLayout.addWidget(self.plot3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.signalsBtn.clicked['bool'].connect(self.vpwvBtn.setEnabled) # type: ignore
        self.signalsBtn.toggled['bool'].connect(self.userMarkersBtn.setEnabled) # type: ignore
        self.signalsBtn.toggled['bool'].connect(self.triggerBtn.setEnabled) # type: ignore
        self.vpwvBtn.toggled['bool'].connect(self.triggerBtn.setDisabled) # type: ignore
        self.signalsBtn.toggled['bool'].connect(self.exitBtn.setDisabled) # type: ignore
        self.exitBtn.clicked.connect(MainWindow.close) # type: ignore
        self.signalsBtn.toggled['bool'].connect(self.fullscreenBtn.setDisabled) # type: ignore
        self.signalsBtn.toggled['bool'].connect(self.dopplerBtn.setDisabled) # type: ignore
        self.dopplerBtn.toggled['bool'].connect(self.signalsBtn.setDisabled) # type: ignore
        self.dopplerBtn.toggled['bool'].connect(self.triggerBtn.setEnabled) # type: ignore
        self.signalsBtn.toggled['bool'].connect(self.saveBtn.setDisabled) # type: ignore
        self.dopplerBtn.toggled['bool'].connect(self.saveBtn.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signalsBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start/Stop acquisition of ECG and Breath signals</p></body></html>"))
        self.vpwvBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start/Stop vPWV measurement routine</p></body></html>"))
        self.triggerBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Single vPWV measurement</p></body></html>"))
        self.dopplerBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start/Stop acquisition of Doppler and Pressure signals</p></body></html>"))
        self.userMarkersBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Put a marker at the present timestamp</p></body></html>"))
        self.TitleLabel.setText(_translate("MainWindow", "Press play to start"))
        self.saveBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Start/Stop acquisition of ECG and Breath signals</p></body></html>"))
        self.settingsBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Settings</p></body></html>"))
        self.fullscreenBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Toggle fullscreen mode</p></body></html>"))
        self.exitBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exit</p></body></html>"))
from Plotter import SignalsPlotter, vpwvPlotter
import Resource_file_rc
