# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_DialogDeltaX.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(529, 221)
        Dialog.setStyleSheet("background-color: rgb(36, 42, 56);\n"
"color:rgb(223, 103, 90);\n"
"font: 75 30pt \"Inter\";")
        Dialog.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        Dialog.setModal(False)
        self.okBtn = QtWidgets.QPushButton(Dialog)
        self.okBtn.setGeometry(QtCore.QRect(230, 150, 71, 63))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okBtn.sizePolicy().hasHeightForWidth())
        self.okBtn.setSizePolicy(sizePolicy)
        self.okBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"  icon: url(:/Icons/GUI_Resources/upload.svg);\n"
"  qproperty-iconSize: 60px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"")
        self.okBtn.setText("")
        self.okBtn.setIconSize(QtCore.QSize(60, 60))
        self.okBtn.setObjectName("okBtn")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(16, 15, 491, 122))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.PatientIDLineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PatientIDLineEdit.sizePolicy().hasHeightForWidth())
        self.PatientIDLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.PatientIDLineEdit.setFont(font)
        self.PatientIDLineEdit.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: rgb(0, 0, 0);")
        self.PatientIDLineEdit.setMaxLength(36)
        self.PatientIDLineEdit.setObjectName("PatientIDLineEdit")
        self.verticalLayout.addWidget(self.PatientIDLineEdit)
        self.deltaxSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.deltaxSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltaxSpinBox.sizePolicy().hasHeightForWidth())
        self.deltaxSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.deltaxSpinBox.setFont(font)
        self.deltaxSpinBox.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"  background-color: rgb(36, 42, 56);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-up.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-down.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QDoubleSpinBox::disabled\n"
"{\n"
"  color: rgb(93, 93, 93);\n"
"}")
        self.deltaxSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deltaxSpinBox.setDecimals(1)
        self.deltaxSpinBox.setMinimum(-100.0)
        self.deltaxSpinBox.setSingleStep(0.5)
        self.deltaxSpinBox.setProperty("value", 35.0)
        self.deltaxSpinBox.setObjectName("deltaxSpinBox")
        self.verticalLayout.addWidget(self.deltaxSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.okBtn.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Patient ID"))
        self.label.setText(_translate("Dialog", "Distance (cm)  "))
import Resource_file_rc
