# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_DialogTh.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogThreshold(object):
    def setupUi(self, DialogThreshold):
        DialogThreshold.setObjectName("DialogThreshold")
        DialogThreshold.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogThreshold.resize(576, 330)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        DialogThreshold.setFont(font)
        DialogThreshold.setStyleSheet("background-color: rgb(36, 42, 56);\n"
"color: rgb(223, 103, 90);\n"
"font: 75 30pt \"Inter\";")
        DialogThreshold.setModal(False)
        self.uploadBtn = QtWidgets.QPushButton(DialogThreshold)
        self.uploadBtn.setGeometry(QtCore.QRect(240, 240, 78, 74))
        self.uploadBtn.setStyleSheet("QPushButton\n"
"{\n"
"  background-color: rgb(223, 103, 90);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"  icon: url(:/Icons/GUI_Resources/upload.svg);\n"
"  qproperty-iconSize: 60px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"  background-color:rgb(255, 116, 103);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"  background-color:rgb(166, 75, 67);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 2px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"  background-color:rgb(36, 42, 56);\n"
"  color:rgb(223, 103, 90);\n"
"  border-width: 0px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"")
        self.uploadBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/GUI_Resources/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadBtn.setIcon(icon)
        self.uploadBtn.setIconSize(QtCore.QSize(60, 60))
        self.uploadBtn.setObjectName("uploadBtn")
        self.layoutWidget = QtWidgets.QWidget(DialogThreshold)
        self.layoutWidget.setGeometry(QtCore.QRect(14, 20, 542, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ecgSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecgSpinBox.sizePolicy().hasHeightForWidth())
        self.ecgSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ecgSpinBox.setFont(font)
        self.ecgSpinBox.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"  background-color: rgb(36, 42, 56);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-up.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-down.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QDoubleSpinBox::disabled\n"
"{\n"
"  color: rgb(93, 93, 93);\n"
"}")
        self.ecgSpinBox.setMinimum(-99.99)
        self.ecgSpinBox.setSingleStep(0.01)
        self.ecgSpinBox.setObjectName("ecgSpinBox")
        self.verticalLayout.addWidget(self.ecgSpinBox)
        self.inflationSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inflationSpinBox.sizePolicy().hasHeightForWidth())
        self.inflationSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.inflationSpinBox.setFont(font)
        self.inflationSpinBox.setStyleSheet("QSpinBox\n"
"{\n"
"  background-color: rgb(36, 42, 56);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-up.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QSpinBox::up-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-down.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QSpinBox::down-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QSpinBox::disabled\n"
"{\n"
"  color: rgb(93, 93, 93);\n"
"}")
        self.inflationSpinBox.setMaximum(999)
        self.inflationSpinBox.setSingleStep(10)
        self.inflationSpinBox.setProperty("value", 100)
        self.inflationSpinBox.setObjectName("inflationSpinBox")
        self.verticalLayout.addWidget(self.inflationSpinBox)
        self.delaySpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.delaySpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delaySpinBox.sizePolicy().hasHeightForWidth())
        self.delaySpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.delaySpinBox.setFont(font)
        self.delaySpinBox.setStyleSheet("QSpinBox\n"
"{\n"
"  background-color: rgb(36, 42, 56);\n"
"  color: rgb(223, 103, 90);\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 5px;\n"
"  border-color: rgb(0, 0, 0);\n"
"  padding: 1px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-up.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QSpinBox::up-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: rgb(223, 103, 90);\n"
"    image: url(:/Icons/GUI_Resources/chevron-down.svg);\n"
"    width: 40px;\n"
"      border-style: solid;\n"
"      border-width: 2px;\n"
"      border-radius: 5px;\n"
"      border-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(255, 116, 103);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    background-color: rgb(157, 71, 63);\n"
"}\n"
"\n"
"QSpinBox::down-button:disabled {\n"
"    background-color: rgb(93, 93, 93);\n"
"}\n"
"\n"
"QSpinBox::disabled\n"
"{\n"
"  color: rgb(93, 93, 93);\n"
"}")
        self.delaySpinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.delaySpinBox.setMaximum(9999)
        self.delaySpinBox.setSingleStep(10)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.verticalLayout.addWidget(self.delaySpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(DialogThreshold)
        self.uploadBtn.clicked.connect(DialogThreshold.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogThreshold)

    def retranslateUi(self, DialogThreshold):
        _translate = QtCore.QCoreApplication.translate
        DialogThreshold.setWindowTitle(_translate("DialogThreshold", "Dialog"))
        self.label_3.setText(_translate("DialogThreshold", "ECG threshold"))
        self.label_4.setText(_translate("DialogThreshold", "Inflation Time"))
        self.label_5.setText(_translate("DialogThreshold", "R-wave Delay"))
import Resource_file_rc
